import React, { useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight, Plus } from "lucide-react";
import { useNavigate } from "react-router-dom";
import {
  addTaskToSession,
  generateSession,
  getPlannerByUser,
  getSessionsByUser,
  getTasksBySession,
} from "../services/api";

import Card from "../components/ui/Card";
import Button from "../components/ui/Button";
import ScheduleHeader from "../components/schedule/ScheduleHeader";

const defaultScheduleData = {
  title: "Study Planner",
  description:
    "Your adaptive plan is generated by the planner and updated after every session.",
};

const SchedulePage = () => {
  const navigate = useNavigate();
  const [scheduleData] = useState(defaultScheduleData);
  const [planner, setPlanner] = useState(null);
  const [sessions, setSessions] = useState([]);
  const [tasksBySession, setTasksBySession] = useState({});
  const [taskInputs, setTaskInputs] = useState({});
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(true);

  const plannedSessions = useMemo(
    () => sessions.filter((session) => session.status === "Planned"),
    [sessions],
  );

  const plannerBanner = useMemo(() => {
    if (!planner) return null;
    const mode = planner.burnoutMode || "Normal";
    if (mode === "Recovery") {
      return {
        label: "Recovery Mode",
        message: "The planner reduced your load to prioritize recovery.",
        className: "bg-rose-50 border-rose-200 text-rose-800",
      };
    }
    if (mode === "Warning") {
      return {
        label: "Warning Mode",
        message: "The planner is pacing you with shorter focus blocks.",
        className: "bg-amber-50 border-amber-200 text-amber-800",
      };
    }
    return {
      label: "Normal Mode",
      message: "The planner set a full focus workload for today.",
      className: "bg-emerald-50 border-emerald-200 text-emerald-800",
    };
  }, [planner]);

  const loadPlannerData = async () => {
    setIsLoading(true);
    try {
      const [plannerData, sessionData] = await Promise.all([
        getPlannerByUser(1).catch(() => null),
        getSessionsByUser(1),
      ]);

      setPlanner(plannerData);
      setSessions(sessionData || []);

      const planned = (sessionData || []).filter(
        (session) => session.status === "Planned",
      );
      const taskPairs = await Promise.all(
        planned.map(async (session) => {
          const sessionId = session.sessionId || session.session_id;
          const tasks = await getTasksBySession(sessionId).catch(() => []);
          return [sessionId, tasks];
        }),
      );

      const taskMap = taskPairs.reduce((acc, [sessionId, tasks]) => {
        acc[sessionId] = tasks;
        return acc;
      }, {});

      setTasksBySession(taskMap);
      setError("");
    } catch (err) {
      setError("Unable to load planner sessions.");
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadPlannerData();
  }, []);

  const handleGenerateSession = async () => {
    setError("");
    try {
      await generateSession(1);
      await loadPlannerData();
    } catch (err) {
      setError("Failed to generate a new session.");
    }
  };

  const handleTaskInputChange = (sessionId, value) => {
    setTaskInputs((prev) => ({ ...prev, [sessionId]: value }));
  };

  const handleAddTask = async (sessionId) => {
    const title = (taskInputs[sessionId] || "").trim();
    if (!title) return;
    setError("");
    try {
      await addTaskToSession(sessionId, {
        title,
        estimatedTime: 30,
        status: "Pending",
      });
      const tasks = await getTasksBySession(sessionId).catch(() => []);
      setTasksBySession((prev) => ({ ...prev, [sessionId]: tasks }));
      setTaskInputs((prev) => ({ ...prev, [sessionId]: "" }));
    } catch (err) {
      setError("Failed to add task to the session.");
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.3 }}
      className="max-w-5xl mx-auto"
    >
      <ScheduleHeader
        title={scheduleData.title}
        description={scheduleData.description}
        error={error}
      />

      {plannerBanner && (
        <div
          className={`border rounded-2xl px-5 py-3.5 mb-6 ${plannerBanner.className}`}
        >
          <p className="font-semibold text-sm">{plannerBanner.label}</p>
          <p className="text-xs opacity-80 mt-0.5">{plannerBanner.message}</p>
        </div>
      )}

      <div className="flex items-center justify-between mb-6">
        <div>
          <p className="text-sm text-slate-500">
            {plannedSessions.length} planned session
            {plannedSessions.length === 1 ? "" : "s"}
          </p>
        </div>
        <Button variant="solid" size="md" onClick={handleGenerateSession}>
          <Plus size={16} />
          Generate Session
        </Button>
      </div>

      <div className="space-y-5">
        {isLoading && (
          <Card className="py-8 text-center text-slate-500">
            Loading planner sessions…
          </Card>
        )}

        {!isLoading && plannedSessions.length === 0 && (
          <Card className="py-8 text-center text-slate-500">
            No planned sessions yet. Generate one to begin.
          </Card>
        )}

        {plannedSessions.map((session) => {
          const sessionId = session.sessionId || session.session_id;
          const tasks = tasksBySession[sessionId] || [];
          const focusDuration =
            session.plannedFocusDuration ||
            session.planned_focus_duration ||
            45;
          const breakInterval =
            session.breakIntervalMinutes ||
            session.break_interval_minutes ||
            45;
          const breakDuration =
            session.plannedBreakDuration ||
            session.planned_break_duration ||
            10;

          return (
            <Card key={sessionId} className="space-y-4">
              <div className="flex flex-wrap items-center justify-between gap-3">
                <div>
                  <p className="text-xs uppercase tracking-widest text-slate-400">
                    Session
                  </p>
                  <h3 className="text-lg font-semibold text-slate-800">
                    Session #{sessionId}
                  </h3>
                  <p className="text-xs text-slate-500 mt-1">
                    Status: {session.status}
                  </p>
                </div>
                <Button
                  variant="solid"
                  size="md"
                  onClick={() => navigate(`/sessions?sessionId=${sessionId}`)}
                >
                  Start Session
                  <ArrowRight size={16} />
                </Button>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-3 text-sm text-slate-600">
                <div className="rounded-xl bg-slate-50 px-4 py-3">
                  Focus: {focusDuration} min
                </div>
                <div className="rounded-xl bg-slate-50 px-4 py-3">
                  Break Interval: {breakInterval} min
                </div>
                <div className="rounded-xl bg-slate-50 px-4 py-3">
                  Break: {breakDuration} min
                </div>
              </div>

              <div>
                <p className="text-xs uppercase tracking-widest text-slate-400 mb-2">
                  Tasks in session
                </p>
                {tasks.length === 0 ? (
                  <p className="text-sm text-slate-500">No tasks added yet.</p>
                ) : (
                  <ul className="space-y-2">
                    {tasks.map((task, index) => (
                      <li
                        key={task.taskId || task.task_id || index}
                        className="flex items-center justify-between rounded-lg border border-slate-100 px-3 py-2 text-sm"
                      >
                        <span className="text-slate-700">{task.title}</span>
                        <span className="text-slate-400">{task.status}</span>
                      </li>
                    ))}
                  </ul>
                )}
              </div>

              <div className="flex flex-wrap items-center gap-3">
                <input
                  type="text"
                  value={taskInputs[sessionId] || ""}
                  onChange={(event) =>
                    handleTaskInputChange(sessionId, event.target.value)
                  }
                  placeholder="Add a task to this session"
                  className="flex-1 min-w-[220px] rounded-xl border border-slate-200 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-sanctuary-500"
                />
                <Button
                  variant="outline"
                  size="md"
                  onClick={() => handleAddTask(sessionId)}
                >
                  Add Task
                </Button>
              </div>
            </Card>
          );
        })}
      </div>
    </motion.div>
  );
};

export default SchedulePage;
